project_name: ssmh
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: ssmh
    ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - tap:
      owner: michimani
      name: homebrew-ssmh
    folder: Formula
    homepage: 'https://github.com/michimani/ssmh'
    description: 'Show the history of connections to Amazon EC2 instances using AWS Session Manager'
    license: 'MIT'